export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_VALIDATION_USERNAME = "AUTH_VALIDATION_USERNAME";
export const AUTH_VALIDATION_EMAIL_SIGNUP = "AUTH_VALIDATION_EMAIL_SIGNUP";
export const AUTH_VALIDATION_EMAIL_VERIFIED = "AUTH_VALIDATION_EMAIL_VERIFIED";
export const AUTH_VALIDATIONS_LOGIN = "AUTH_VALIDATIONS_LOGIN";
export const AUTH_VALIDATIONS_SEND_MAIL_RESET_PASSWORD =
  "AUTH_VALIDATIONS_SEND_MAIL_RESET_PASSWORD";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_SENDED_EMAIL_WITH_LINK_RESET_PASSWORD =
  "AUTH_SENDED_EMAIL_WITH_LINK_RESET_PASSWORD";
export const AUTH_FACEBOOK_LOGIN_SUCCESS = "AUTH_FACEBOOK_LOGIN_SUCCESS";
export const AUTH_GOOGLE_LOGIN_SUCCESS = "AUTH_GOOGLE_LOGIN_SUCCESS";
export const AUTH_AUTO_LOGIN_SUCCESS = "AUTH_AUTO_LOGIN_SUCCESS";
export const AUTH_AUTO_LOGIN = "AUTH_AUTO_LOGIN";
export const AUTH_DATA = "AUTH_DATA";
export const ADDED_NEW_PLACE = "ADDED_NEW_PLACE";
export const SET_RESTAURANT_AVATAR = "SET_RESTAURANT_AVATAR";
export const SET_RESTAURANT_HEADER = "SET_RESTAURANT_HEADER";
export const SET_RESTAURANT_MENU = "SET_RESTAURANT_MENU";
export const OWNER_HAVE_EATING_PLACE = "OWNER_HAVE_EATING_PLACE";
export const RETURN_CODE_FOR_CLIENT = "RETURN_CODE_FOR_CLIENT";
export const CLIENT_CODE_IS_VERIFIED = "CLIENT_CODE_IS_VERIFIED";
export const BLOCKED_OPINION_FORM = "BLOCKED_OPINION_FORM";
export const SHOW_CLIENTS_OPINIONS = "SHOW_CLIENTS_OPINIONS";
export const INVALID_FORMAT_IMAGES_EATING_PLACE =
  "INVALID_FORMAT_IMAGES_EATING_PLACE";
export const UNAVAILABLE_ALL_IMAGES_EATING_PLACE =
  "UNAVAILABLE_ALL_IMAGES_EATING_PLACE";
export const UPLOAD_IMAGES_EATING_PLACE_IS_FAIL =
  "UPLOAD_IMAGES_EATING_PLACE_IS_FAIL";
export const ADDED_OWNER_POST = "ADDED_OWNER_POST";
export const UPDATED_OWNER_POST = "UPDATED_OWNER_POST";
export const EMAIL_VERIFICATED = "EMAIL_VERIFICATED";
export const UPDATED_CLIENTS_OPINIONS = "UPDATED_CLIENTS_OPINIONS";
export const TOO_MANY_ATTEMPTS_LOG_IN_TRY_LATER =
  "TOO_MANY_ATTEMPTS_LOG_IN_TRY_LATER";
export const SEARCHED_EATING_PLACES = "SEARCHED_EATING_PLACES";
export const SINGLE_EATING_PLACE = "SINGLE_EATING_PLACE";
export const NOT_ADDED_EATING_PLACE = "NOT_ADDED_EATING_PLACE";
export const ACCOUNT_DATA = "ACCOUNT_DATA";
export const EDITED_BASIC_USERDATA = "EDITED_BASIC_USERDATA";
