export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_VALIDATION_MESSAGE = "AUTH_VALIDATION_MESSAGE";
export const AUTH_VALIDATION_USERNAME = "AUTH_VALIDATION_USERNAME";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
