export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_VALIDATION_USERNAME = "AUTH_VALIDATION_USERNAME";
export const AUTH_VALIDATION_EMAIL_SIGNUP = "AUTH_VALIDATION_EMAIL_SIGNUP";
export const AUTH_VALIDATION_EMAIL_VERIFIED = "AUTH_VALIDATION_EMAIL_VERIFIED";
export const AUTH_VALIDATIONS_LOGIN = "AUTH_VALIDATIONS_LOGIN";
export const AUTH_VALIDATIONS_FORGOT_PASSWORD =
  "AUTH_VALIDATIONS_FORGOT_PASSWORD";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
